sudo: required
language: bash
services:
- docker
env:
  global:
    secure: JsElSc+zugQ0b0PVF1Mr+04qFlMx+yz8w2JHGWkw0/e/FNe6ewSj4WhqI+vaHZnwukQg8t3AE/fRUkHwGZZ8T2SYk97+HDjFHnN1YycAheKW7d9C53x3HNV3rXvzGkfYXSAehhprAXCxkdXMUG97O8kkZ26B32g/jJJv0cnOM/xYuDa2WEZnM+S0Fh0sYady5s2SDBX9qHO2K6UHS8puHw9BSz1/KX/+nn4ZvfTRy8zOedMzHM5p+Wc6dHPiR1NZnZJcLy5GHzN2l5NJUfXvMvIQ60cWnqlzO8baVG1tKpeDyioYkoTHz2HwHgUgfUJvUoOWBSU5d+3x0LjD2cXa0UmfWHADCSuCUNTFAYAK8uOVQi388nq7RdFfVdULYCSrROUBoYMxMQaURQ5pEaonw8LfkHGdvpceD8TohnUQjDKzE2LA7DyhD1c3EM00cOIfiPf0kj9V/qrcfruf/lo8LU2rVq8X97B66hyo6T8UYpFpPZN8Z1BoSeDy69QQVpPVkdQIJY0lTilHyZmlh8LPcb1SO+ZZdoJPQjTkJU2t/U/P7cEHwtWMUyiuYHmylGx2Lcdpgvpic23RvcNVdvEVCNDtMk1ZUM++XL3xx4P4VCpfJjSeSzs79dE8iGHQmIagvv384tWhuIBC3akh3HhO4YJOSbt/7UJX39i6qJWqUMo=
  matrix:
  - ARCH=armhf GOARCH=arm   GOARM=6 QEMU_ARCH=arm     TAG=arm
  - ARCH=arm64 GOARCH=arm64 GOARM=6 QEMU_ARCH=arm64   TAG=arm64
before_install:
- curl -L https://goss.rocks/install | sudo sh
- sudo apt-get -y install qemu-user-static
- docker run --rm --privileged multiarch/qemu-user-static:register
script:
- docker build -t visibilityspots/fabio:$TAG --build-arg ARCH="$ARCH" --build-arg
  GOARCH="$GOARCH" --build-arg GOARM="$GOARM" ./
- dgoss run --name fabio -ti visibilityspots/fabio:$TAG
after_success:
- if [ "$TRAVIS_BRANCH" == "master" ]; then docker login -u=visibilityspots -p="$DOCKER_PASSWORD";
  docker push visibilityspots/fabio:$TAG; fi
